In [10]:
import numpy as np
import random

# Question 1
> ## Create a Numpy Array named arr that contains every integer from 0 to 100 (inclusive)

In [4]:
# A hardcoded, but inefficient solution
arr = np.ones(51)
y = 0
for i, x in enumerate(arr):
  arr[i] = y
  y += 2
print("Solution 1: ", arr)

# using numpy features    
arr = np.arange(0,102,2)
print("Solution 2: ", arr)

# Alternatively
arr = np.linspace(0, 100, 51)
print("Solution 3: ", arr)

Solution 1:  [  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]
Solution 2:  [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
Solution 3:  [  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]


# Question 2
> ## Reverse the order of arr

In [9]:
# A pythonic solution
arr = arr[::-1]
print(arr)
# a solution using numpy features
arr = np.flipud(arr)
print(arr)


[  0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.
  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.
  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.
  84.  86.  88.  90.  92.  94.  96.  98. 100.]


# Question 3
> ## Create a 3x3 array and populate it with random integers from 1-999. Return the maximum value from each row. 

In [17]:
#The Solution
arr = np.random.randint(1, 1000, size=(3, 3))
maxlist = np.amax(arr, axis=1)
print(arr)
print("Maximum Value for Row 1: ", maxlist[0])
print("Maximum Value for Row 2: ", maxlist[1])
print("Maximum Value for Row 3: ", maxlist[2])

[[556 127 528]
 [189 818 791]
 [183 736 680]]
Maximum Value for Row 1:  556
Maximum Value for Row 2:  818
Maximum Value for Row 3:  736
